server:
  port: 8084

spring:
  application:
    name: orderservice
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: Himosh1020
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    consumer:
#      group-id: order-service-group
#      auto-offset-reset: earliest
#      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: 'com.mini_project.orderservice.model.dto'
#          deserializer:
#            key.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#            value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#
#

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
